def my_exception():
    try:
        print("Logical Python")
        return
    finally:
        print("is the Best")

my_exception()